name: Enable auto-merge for Dependabot pull requests

on:
  pull_request_target:
    types: [opened, reopened, labeled, synchronize]

jobs:
  enable-automerge:
    # Only run for Dependabot PRs that include the `automerge` label
    if: contains(join(github.event.pull_request.labels.*.name, ','), 'automerge') && (github.event.pull_request.user.login == 'dependabot[bot]' || contains(github.event.pull_request.user.login, 'dependabot'))
    runs-on: ubuntu-latest
    steps:
      - name: Enable GitHub auto-merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
